name: tonarede
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  graphql_flutter: ^5.1.2
  http: ^0.13.6

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - images/
  fonts: 
    - family: Signatra
      fonts: 
        - asset: fonts/Signatra.ttf
    - family: Brand-Regular
      fonts: 
        - asset: fonts/bolt-regular.ttf
    - family: Brand Bold
      fonts: 
        - asset: fonts/bolt-semibold.ttf
  uses-material-design: true

